let countdown = 10;
setTimeout(()=>{
    document.getElementById("display").innerHTML=countdown--;
    setTimeout(()=>{
        document.getElementById("display").innerHTML=countdown--;
        setTimeout(()=>{
            document.getElementById("display").innerHTML=countdown--;
            setTimeout(()=>{
                document.getElementById("display").innerHTML=countdown--;
                setTimeout(()=>{
                    document.getElementById("display").innerHTML=countdown--;
                    setTimeout(()=>{
                        document.getElementById("display").innerHTML=countdown--;
                        setTimeout(()=>{
                            document.getElementById("display").innerHTML=countdown--;
                            setTimeout(()=>{
                                document.getElementById("display").innerHTML=countdown--;
                                setTimeout(()=>{
                                    document.getElementById("display").innerHTML=countdown--;
                                    setTimeout(()=>{
                                        document.getElementById("display").innerHTML=countdown--;
                                        setTimeout(()=>{
                                            document.getElementById("display").innerHTML="Happy Independence Day ";
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)    
},1000)